<?php

namespace Database\Seeders;

use App\Models\Country;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountriesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        Country::truncate();

        $countries = [
            ['name' => 'Afghanistan', 'id' => 'AF', 'continent_id' => 'AS'],
            ['name' => 'Åland Islands', 'id' => 'AX', 'continent_id' => 'EU'],
            ['name' => 'Albania', 'id' => 'AL', 'continent_id' => 'EU'],
            ['name' => 'Algeria', 'id' => 'DZ', 'continent_id' => 'AF'],
            ['name' => 'American Samoa', 'id' => 'AS', 'continent_id' => 'OC'],
            ['name' => 'Andorra', 'id' => 'AD', 'continent_id' => 'EU'],
            ['name' => 'Angola', 'id' => 'AO', 'continent_id' => 'AF'],
            ['name' => 'Anguilla', 'id' => 'AI', 'continent_id' => 'NA'],
            ['name' => 'Antarctica', 'id' => 'AQ', 'continent_id' => 'AN'],
            ['name' => 'Antigua and Barbuda', 'id' => 'AG', 'continent_id' => 'NA'],
            ['name' => 'Argentina', 'id' => 'AR', 'continent_id' => 'SA'],
            ['name' => 'Armenia', 'id' => 'AM', 'continent_id' => 'AS'],
            ['name' => 'Aruba', 'id' => 'AW', 'continent_id' => 'NA'],
            ['name' => 'Australia', 'id' => 'AU', 'continent_id' => 'OC'],
            ['name' => 'Austria', 'id' => 'AT', 'continent_id' => 'EU'],
            ['name' => 'Azerbaijan', 'id' => 'AZ', 'continent_id' => 'AS'],
            ['name' => 'Bahamas', 'id' => 'BS', 'continent_id' => 'NA'],
            ['name' => 'Bahrain', 'id' => 'BH', 'continent_id' => 'AS'],
            ['name' => 'Bangladesh', 'id' => 'BD', 'continent_id' => 'AS'],
            ['name' => 'Barbados', 'id' => 'BB', 'continent_id' => 'NA'],
            ['name' => 'Belarus', 'id' => 'BY', 'continent_id' => 'EU'],
            ['name' => 'Belgium', 'id' => 'BE', 'continent_id' => 'EU'],
            ['name' => 'Belize', 'id' => 'BZ', 'continent_id' => 'NA'],
            ['name' => 'Benin', 'id' => 'BJ', 'continent_id' => 'AF'],
            ['name' => 'Bermuda', 'id' => 'BM', 'continent_id' => 'NA'],
            ['name' => 'Bhutan', 'id' => 'BT', 'continent_id' => 'AS'],
            ['name' => 'Bolivia, Plurinational State of', 'id' => 'BO', 'continent_id' => 'SA'],
            ['name' => 'Bonaire, Sint Eustatius and Saba', 'id' => 'BQ', 'continent_id' => 'NA'],
            ['name' => 'Bosnia and Herzegovina', 'id' => 'BA', 'continent_id' => 'EU'],
            ['name' => 'Botswana', 'id' => 'BW', 'continent_id' => 'AF'],
            ['name' => 'Bouvet Island', 'id' => 'BV', 'continent_id' => 'AN'],
            ['name' => 'Brazil', 'id' => 'BR', 'continent_id' => 'SA'],
            ['name' => 'British Indian Ocean Territory', 'id' => 'IO', 'continent_id' => 'AF'],
            ['name' => 'Brunei Darussalam', 'id' => 'BN', 'continent_id' => 'AS'],
            ['name' => 'Bulgaria', 'id' => 'BG', 'continent_id' => 'EU'],
            ['name' => 'Burkina Faso', 'id' => 'BF', 'continent_id' => 'AF'],
            ['name' => 'Burundi', 'id' => 'BI', 'continent_id' => 'AF'],
            ['name' => 'Cambodia', 'id' => 'KH', 'continent_id' => 'AS'],
            ['name' => 'Cameroon', 'id' => 'CM', 'continent_id' => 'AF'],
            ['name' => 'Canada', 'id' => 'CA', 'continent_id' => 'NA'],
            ['name' => 'Cape Verde', 'id' => 'CV', 'continent_id' => 'AF'],
            ['name' => 'Cayman Islands', 'id' => 'KY', 'continent_id' => 'NA'],
            ['name' => 'Central African Republic', 'id' => 'CF', 'continent_id' => 'AF'],
            ['name' => 'Chad', 'id' => 'TD', 'continent_id' => 'AF'],
            ['name' => 'Chile', 'id' => 'CL', 'continent_id' => 'SA'],
            ['name' => 'China', 'id' => 'CN', 'continent_id' => 'AS'],
            ['name' => 'Christmas Island', 'id' => 'CX', 'continent_id' => 'AS'],
            ['name' => 'Cocos (Keeling) Islands', 'id' => 'CC', 'continent_id' => 'AS'],
            ['name' => 'Colombia', 'id' => 'CO', 'continent_id' => 'SA'],
            ['name' => 'Comoros', 'id' => 'KM', 'continent_id' => 'AF'],
            ['name' => 'Congo', 'id' => 'CG', 'continent_id' => 'AF'],
            ['name' => 'Congo, the Democratic Republic of the', 'id' => 'CD', 'continent_id' => 'AF'],
            ['name' => 'Cook Islands', 'id' => 'CK', 'continent_id' => 'OC'],
            ['name' => 'Costa Rica', 'id' => 'CR', 'continent_id' => 'NA'],
            ['name' => 'Côte d\'Ivoire', 'id' => 'CI', 'continent_id' => 'AF'],
            ['name' => 'Croatia', 'id' => 'HR', 'continent_id' => 'EU'],
            ['name' => 'Cuba', 'id' => 'CU', 'continent_id' => 'NA'],
            ['name' => 'Curaçao', 'id' => 'CW', 'continent_id' => 'NA'],
            ['name' => 'Cyprus', 'id' => 'CY', 'continent_id' => 'EU'],
            ['name' => 'Czech Republic', 'id' => 'CZ', 'continent_id' => 'EU'],
            ['name' => 'Denmark', 'id' => 'DK', 'continent_id' => 'EU'],
            ['name' => 'Djibouti', 'id' => 'DJ', 'continent_id' => 'AF'],
            ['name' => 'Dominica', 'id' => 'DM', 'continent_id' => 'NA'],
            ['name' => 'Dominican Republic', 'id' => 'DO', 'continent_id' => 'NA'],
            ['name' => 'Ecuador', 'id' => 'EC', 'continent_id' => 'SA'],
            ['name' => 'Egypt', 'id' => 'EG', 'continent_id' => 'AS'],
            ['name' => 'El Salvador', 'id' => 'SV', 'continent_id' => 'NA'],
            ['name' => 'Equatorial Guinea', 'id' => 'GQ', 'continent_id' => 'AF'],
            ['name' => 'Eritrea', 'id' => 'ER', 'continent_id' => 'AF'],
            ['name' => 'Estonia', 'id' => 'EE', 'continent_id' => 'EU'],
            ['name' => 'Ethiopia', 'id' => 'ET', 'continent_id' => 'AF'],
            ['name' => 'Falkland Islands (Malvinas)', 'id' => 'FK', 'continent_id' => 'SA'],
            ['name' => 'Faroe Islands', 'id' => 'FO', 'continent_id' => 'EU'],
            ['name' => 'Fiji', 'id' => 'FJ', 'continent_id' => 'OC'],
            ['name' => 'Finland', 'id' => 'FI', 'continent_id' => 'EU'],
            ['name' => 'France', 'id' => 'FR', 'continent_id' => 'EU'],
            ['name' => 'French Guiana', 'id' => 'GF', 'continent_id' => 'SA'],
            ['name' => 'French Polynesia', 'id' => 'PF', 'continent_id' => 'OC'],
            ['name' => 'French Southern Territories', 'id' => 'TF', 'continent_id' => 'AF'],
            ['name' => 'Gabon', 'id' => 'GA', 'continent_id' => 'AF'],
            ['name' => 'Gambia', 'id' => 'GM', 'continent_id' => 'AF'],
            ['name' => 'Georgia', 'id' => 'GE', 'continent_id' => 'AS'],
            ['name' => 'Germany', 'id' => 'DE', 'continent_id' => 'EU'],
            ['name' => 'Ghana', 'id' => 'GH', 'continent_id' => 'AF'],
            ['name' => 'Gibraltar', 'id' => 'GI', 'continent_id' => 'EU'],
            ['name' => 'Greece', 'id' => 'GR', 'continent_id' => 'EU'],
            ['name' => 'Greenland', 'id' => 'GL', 'continent_id' => 'NA'],
            ['name' => 'Grenada', 'id' => 'GD', 'continent_id' => 'NA'],
            ['name' => 'Guadeloupe', 'id' => 'GP', 'continent_id' => 'NA'],
            ['name' => 'Guam', 'id' => 'GU', 'continent_id' => 'OC'],
            ['name' => 'Guatemala', 'id' => 'GT', 'continent_id' => 'NA'],
            ['name' => 'Guernsey', 'id' => 'GG', 'continent_id' => 'EU'],
            ['name' => 'Guinea', 'id' => 'GN', 'continent_id' => 'AF'],
            ['name' => 'Guinea-Bissau', 'id' => 'GW', 'continent_id' => 'AF'],
            ['name' => 'Guyana', 'id' => 'GY', 'continent_id' => 'SA'],
            ['name' => 'Haiti', 'id' => 'HT', 'continent_id' => 'NA'],
            ['name' => 'Heard Island and McDonald Islands', 'id' => 'HM', 'continent_id' => 'AN'],
            ['name' => 'Holy See (Vatican City State)', 'id' => 'VA', 'continent_id' => 'EU'],
            ['name' => 'Honduras', 'id' => 'HN', 'continent_id' => 'NA'],
            ['name' => 'Hong Kong', 'id' => 'HK', 'continent_id' => 'AS'],
            ['name' => 'Hungary', 'id' => 'HU', 'continent_id' => 'EU'],
            ['name' => 'Iceland', 'id' => 'IS', 'continent_id' => 'EU'],
            ['name' => 'India', 'id' => 'IN', 'continent_id' => 'AS'],
            ['name' => 'Indonesia', 'id' => 'ID', 'continent_id' => 'AS'],
            ['name' => 'Iran, Islamic Republic of', 'id' => 'IR', 'continent_id' => 'AS'],
            ['name' => 'Iraq', 'id' => 'IQ', 'continent_id' => 'AS'],
            ['name' => 'Ireland', 'id' => 'IE', 'continent_id' => 'EU'],
            ['name' => 'Isle of Man', 'id' => 'IM', 'continent_id' => 'EU'],
            ['name' => 'Israel', 'id' => 'IL', 'continent_id' => 'AS'],
            ['name' => 'Italy', 'id' => 'IT', 'continent_id' => 'EU'],
            ['name' => 'Jamaica', 'id' => 'JM', 'continent_id' => 'NA'],
            ['name' => 'Japan', 'id' => 'JP', 'continent_id' => 'AS'],
            ['name' => 'Jersey', 'id' => 'JE', 'continent_id' => 'EU'],
            ['name' => 'Jordan', 'id' => 'JO', 'continent_id' => 'AS'],
            ['name' => 'Kazakhstan', 'id' => 'KZ', 'continent_id' => 'AS'],
            ['name' => 'Kenya', 'id' => 'KE', 'continent_id' => 'AF'],
            ['name' => 'Kiribati', 'id' => 'KI', 'continent_id' => 'OC'],
            ['name' => 'Korea, Democratic People\'s Republic of', 'id' => 'KP', 'continent_id' => 'AS'],
            ['name' => 'Korea, Republic of', 'id' => 'KR', 'continent_id' => 'AS'],
            ['name' => 'Kuwait', 'id' => 'KW', 'continent_id' => 'AS'],
            ['name' => 'Kyrgyzstan', 'id' => 'KG', 'continent_id' => 'AS'],
            ['name' => 'Lao People\'s Democratic Republic', 'id' => 'LA', 'continent_id' => 'AS'],
            ['name' => 'Latvia', 'id' => 'LV', 'continent_id' => 'EU'],
            ['name' => 'Lebanon', 'id' => 'LB', 'continent_id' => 'AS'],
            ['name' => 'Lesotho', 'id' => 'LS', 'continent_id' => 'AF'],
            ['name' => 'Liberia', 'id' => 'LR', 'continent_id' => 'AF'],
            ['name' => 'Libya', 'id' => 'LY', 'continent_id' => 'AF'],
            ['name' => 'Liechtenstein', 'id' => 'LI', 'continent_id' => 'EU'],
            ['name' => 'Lithuania', 'id' => 'LT', 'continent_id' => 'EU'],
            ['name' => 'Luxembourg', 'id' => 'LU', 'continent_id' => 'EU'],
            ['name' => 'Macao', 'id' => 'MO', 'continent_id' => 'AS'],
            ['name' => 'Macedonia, the Former Yugoslav Republic of', 'id' => 'MK', 'continent_id' => 'AS'],
            ['name' => 'Madagascar', 'id' => 'MG', 'continent_id' => 'AF'],
            ['name' => 'Malawi', 'id' => 'MW', 'continent_id' => 'AF'],
            ['name' => 'Malaysia', 'id' => 'MY', 'continent_id' => 'AS'],
            ['name' => 'Maldives', 'id' => 'MV', 'continent_id' => 'AS'],
            ['name' => 'Mali', 'id' => 'ML', 'continent_id' => 'AF'],
            ['name' => 'Malta', 'id' => 'MT', 'continent_id' => 'EU'],
            ['name' => 'Marshall Islands', 'id' => 'MH', 'continent_id' => 'OC'],
            ['name' => 'Martinique', 'id' => 'MQ', 'continent_id' => 'NA'],
            ['name' => 'Mauritania', 'id' => 'MR', 'continent_id' => 'AF'],
            ['name' => 'Mauritius', 'id' => 'MU', 'continent_id' => 'AF'],
            ['name' => 'Mayotte', 'id' => 'YT', 'continent_id' => 'AF'],
            ['name' => 'Mexico', 'id' => 'MX', 'continent_id' => 'NA'],
            ['name' => 'Micronesia, Federated States of', 'id' => 'FM', 'continent_id' => 'OC'],
            ['name' => 'Moldova, Republic of', 'id' => 'MD', 'continent_id' => 'EU'],
            ['name' => 'Monaco', 'id' => 'MC', 'continent_id' => 'EU'],
            ['name' => 'Mongolia', 'id' => 'MN', 'continent_id' => 'AS'],
            ['name' => 'Montenegro', 'id' => 'ME', 'continent_id' => 'EU'],
            ['name' => 'Montserrat', 'id' => 'MS', 'continent_id' => 'NA'],
            ['name' => 'Morocco', 'id' => 'MA', 'continent_id' => 'AF'],
            ['name' => 'Mozambique', 'id' => 'MZ', 'continent_id' => 'AF'],
            ['name' => 'Myanmar', 'id' => 'MM', 'continent_id' => 'AS'],
            ['name' => 'Namibia', 'id' => 'NA', 'continent_id' => 'NA'],
            ['name' => 'Nauru', 'id' => 'NR', 'continent_id' => 'OC'],
            ['name' => 'Nepal', 'id' => 'NP', 'continent_id' => 'AS'],
            ['name' => 'Netherlands', 'id' => 'NL', 'continent_id' => 'EU'],
            ['name' => 'New Caledonia', 'id' => 'NC', 'continent_id' => 'OC'],
            ['name' => 'New Zealand', 'id' => 'NZ', 'continent_id' => 'OC'],
            ['name' => 'Nicaragua', 'id' => 'NI', 'continent_id' => 'NA'],
            ['name' => 'Niger', 'id' => 'NE', 'continent_id' => 'AF'],
            ['name' => 'Nigeria', 'id' => 'NG', 'continent_id' => 'AF'],
            ['name' => 'Niue', 'id' => 'NU', 'continent_id' => 'OC'],
            ['name' => 'Norfolk Island', 'id' => 'NF', 'continent_id' => 'OC'],
            ['name' => 'Northern Mariana Islands', 'id' => 'MP', 'continent_id' => 'EU'],
            ['name' => 'Norway', 'id' => 'NO', 'continent_id' => 'EU'],
            ['name' => 'Oman', 'id' => 'OM', 'continent_id' => 'AS'],
            ['name' => 'Pakistan', 'id' => 'PK', 'continent_id' => 'NA'],
            ['name' => 'Palau', 'id' => 'PW', 'continent_id' => 'OC'],
            ['name' => 'Palestine, State of', 'id' => 'PS', 'continent_id' => 'AS'],
            ['name' => 'Panama', 'id' => 'PA', 'continent_id' => 'NA'],
            ['name' => 'Papua New Guinea', 'id' => 'PG', 'continent_id' => 'OC'],
            ['name' => 'Paraguay', 'id' => 'PY', 'continent_id' => 'SA'],
            ['name' => 'Peru', 'id' => 'PE', 'continent_id' => 'SA'],
            ['name' => 'Philippines', 'id' => 'PH', 'continent_id' => 'AS'],
            ['name' => 'Pitcairn', 'id' => 'PN', 'continent_id' => 'OC'],
            ['name' => 'Poland', 'id' => 'PL', 'continent_id' => 'EU'],
            ['name' => 'Portugal', 'id' => 'PT', 'continent_id' => 'EU'],
            ['name' => 'Puerto Rico', 'id' => 'PR', 'continent_id' => 'NA'],
            ['name' => 'Qatar', 'id' => 'QA', 'continent_id' => 'AS'],
            ['name' => 'Réunion', 'id' => 'RE', 'continent_id' => 'AF'],
            ['name' => 'Romania', 'id' => 'RO', 'continent_id' => 'EU'],
            ['name' => 'Russian Federation', 'id' => 'RU', 'continent_id' => 'AS'],
            ['name' => 'Rwanda', 'id' => 'RW', 'continent_id' => 'AF'],
            ['name' => 'Saint Barthélemy', 'id' => 'BL', 'continent_id' => 'NA'],
            ['name' => 'Saint Helena, Ascension and Tristan da Cunha', 'id' => 'SH', 'continent_id' => 'AF'],
            ['name' => 'Saint Kitts and Nevis', 'id' => 'KN', 'continent_id' => 'NA'],
            ['name' => 'Saint Lucia', 'id' => 'LC', 'continent_id' => 'NA'],
            ['name' => 'Saint Martin (French part)', 'id' => 'MF', 'continent_id' => 'NA'],
            ['name' => 'Saint Pierre and Miquelon', 'id' => 'PM', 'continent_id' => 'NA'],
            ['name' => 'Saint Vincent and the Grenadines', 'id' => 'VC', 'continent_id' => 'NA'],
            ['name' => 'Samoa', 'id' => 'WS', 'continent_id' => 'OC'],
            ['name' => 'San Marino', 'id' => 'SM', 'continent_id' => 'EU'],
            ['name' => 'Sao Tome and Principe', 'id' => 'ST', 'continent_id' => 'AF'],
            ['name' => 'Saudi Arabia', 'id' => 'SA', 'continent_id' => 'AS'],
            ['name' => 'Senegal', 'id' => 'SN', 'continent_id' => 'AF'],
            ['name' => 'Serbia', 'id' => 'RS', 'continent_id' => 'EU'],
            ['name' => 'Seychelles', 'id' => 'SC', 'continent_id' => 'AF'],
            ['name' => 'Sierra Leone', 'id' => 'SL', 'continent_id' => 'AF'],
            ['name' => 'Singapore', 'id' => 'SG', 'continent_id' => 'AS'],
            ['name' => 'Sint Maarten (Dutch part)', 'id' => 'SX', 'continent_id' => 'NA'],
            ['name' => 'Slovakia', 'id' => 'SK', 'continent_id' => 'EU'],
            ['name' => 'Slovenia', 'id' => 'SI', 'continent_id' => 'EU'],
            ['name' => 'Solomon Islands', 'id' => 'SB', 'continent_id' => 'OC'],
            ['name' => 'Somalia', 'id' => 'SO', 'continent_id' => 'AF'],
            ['name' => 'South Africa', 'id' => 'ZA', 'continent_id' => 'AF'],
            ['name' => 'South Georgia and the South Sandwich Islands', 'id' => 'GS', 'continent_id' => 'AN'],
            ['name' => 'South Sudan', 'id' => 'SS', 'continent_id' => 'AF'],
            ['name' => 'Spain', 'id' => 'ES', 'continent_id' => 'EU'],
            ['name' => 'Sri Lanka', 'id' => 'LK', 'continent_id' => 'AS'],
            ['name' => 'Sudan', 'id' => 'SD', 'continent_id' => 'AF'],
            ['name' => 'Suriname', 'id' => 'SR', 'continent_id' => 'SA'],
            ['name' => 'Svalbard and Jan Mayen', 'id' => 'SJ', 'continent_id' => 'EU'],
            ['name' => 'Swaziland', 'id' => 'SZ', 'continent_id' => 'AF'],
            ['name' => 'Sweden', 'id' => 'SE', 'continent_id' => 'EU'],
            ['name' => 'Switzerland', 'id' => 'CH', 'continent_id' => 'EU'],
            ['name' => 'Syrian Arab Republic', 'id' => 'SY', 'continent_id' => 'AS'],
            ['name' => 'Taiwan', 'id' => 'TW', 'continent_id' => 'AS'],
            ['name' => 'Tajikistan', 'id' => 'TJ', 'continent_id' => 'AS'],
            ['name' => 'Tanzania, United Republic of', 'id' => 'TZ', 'continent_id' => 'AF'],
            ['name' => 'Thailand', 'id' => 'TH', 'continent_id' => 'AS'],
            ['name' => 'Timor-Leste', 'id' => 'TL', 'continent_id' => 'AS'],
            ['name' => 'Togo', 'id' => 'TG', 'continent_id' => 'AF'],
            ['name' => 'Tokelau', 'id' => 'TK', 'continent_id' => 'OC'],
            ['name' => 'Tonga', 'id' => 'TO', 'continent_id' => 'OC'],
            ['name' => 'Trinidad and Tobago', 'id' => 'TT', 'continent_id' => 'NA'],
            ['name' => 'Tunisia', 'id' => 'TN', 'continent_id' => 'AF'],
            ['name' => 'Turkey', 'id' => 'TR', 'continent_id' => 'AS'],
            ['name' => 'Turkmenistan', 'id' => 'TM', 'continent_id' => 'AS'],
            ['name' => 'Turks and Caicos Islands', 'id' => 'TC', 'continent_id' => 'NA'],
            ['name' => 'Tuvalu', 'id' => 'TV', 'continent_id' => 'OC'],
            ['name' => 'Uganda', 'id' => 'UG', 'continent_id' => 'AF'],
            ['name' => 'Ukraine', 'id' => 'UA', 'continent_id' => 'EU'],
            ['name' => 'United Arab Emirates', 'id' => 'AE', 'continent_id' => 'AS'],
            ['name' => 'United Kingdom', 'id' => 'GB', 'continent_id' => 'EU'],
            ['name' => 'United States', 'id' => 'US', 'continent_id' => 'NA'],
            ['name' => 'United States Minor Outlying Islands', 'id' => 'UM', 'continent_id' => 'NA'],
            ['name' => 'Uruguay', 'id' => 'UY', 'continent_id' => 'SA'],
            ['name' => 'Uzbekistan', 'id' => 'UZ', 'continent_id' => 'AS'],
            ['name' => 'Vanuatu', 'id' => 'VU', 'continent_id' => 'OC'],
            ['name' => 'Venezuela, Bolivarian Republic of', 'id' => 'VE', 'continent_id' => 'SA'],
            ['name' => 'Vietnam', 'id' => 'VN', 'continent_id' => 'AS'],
            ['name' => 'Virgin Islands, British', 'id' => 'VG', 'continent_id' => 'NA'],
            ['name' => 'Virgin Islands, U.S.', 'id' => 'VI', 'continent_id' => 'NA'],
            ['name' => 'Wallis and Futuna', 'id' => 'WF', 'continent_id' => 'OC'],
            ['name' => 'Western Sahara', 'id' => 'EH', 'continent_id' => 'AF'],
            ['name' => 'Yemen', 'id' => 'YE', 'continent_id' => 'AS'],
            ['name' => 'Zambia', 'id' => 'ZM', 'continent_id' => 'AF'],
            ['name' => 'Zimbabwe', 'id' => 'ZW', 'continent_id' => 'AF'],
        ];

        foreach ($countries as $country => $ct) {
            DB::table('countries')->insert($ct);
        }
    }
}
